image : alpine:3.17
#
default:
  before_script:
    - apk update
    - apk add --no-cache openssh-client openssh sshpass zip
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan $SSH_DEPLOY_URL >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

stages:
  - deploy


deploy:
  tags:
  - docker
  stage: deploy
  script:
    - pwd
    - ls
    # zip folder app and send to server
    - zip -r app-php-ramadhan.zip app public composer.json
    - scp app-php-ramadhan.zip $SSH_DEPLOY_USER@$SSH_DEPLOY_URL:$SSH_HOME_URL
    - sshpass -v ssh -t "$SSH_DEPLOY_USER@$SSH_DEPLOY_URL" 'rm -rf app-php-ramadhan; mkdir app-php-ramadhan; unzip app-php-ramadhan.zip -d app-php-ramadhan; cd app-php-ramadhan; ls; cd /opt/tpaz/production/vpsGolang/www/virtual/ramadhan.t-paz.com/; sudo rm -rf app.bak; sudo mv app app.bak; cd public; sudo mv static static.bak; sudo rm -rf static.bak; cd /home/ubuntu/app-php-ramadhan; sudo mv app /opt/tpaz/production/vpsGolang/www/virtual/ramadhan.t-paz.com/; sudo mv composer.json /opt/tpaz/production/vpsGolang/www/virtual/ramadhan.t-paz.com/; cd /home/ubuntu/app-php-ramadhan/public; sudo mv static /opt/tpaz/production/vpsGolang/www/virtual/ramadhan.t-paz.com/public/; ls /opt/tpaz/production/vpsGolang/www/virtual/ramadhan.t-paz.com/public/;'
   

